SELECT AVETAID AS MEMBERID,
       TERMDATE,
       LANGUAGECODE
FROM   ENTERPRISEINTERFACES.CVS.CVSSQELETONLAYOUT AS CV
       LEFT OUTER JOIN ENTERPRISEHUB.DBO.MEMBERINDICATOR AS MI
       ON CV.MEMBERID = MI.MEMBERRECID
       INNER JOIN ENTERPRISEHUB.DBO.MEMBERCOMPANY AS MC
       ON MI.MEMBERRECID = MC.MEMBERRECID
          AND MI.INDMREFID = 24
          AND (ISNULL(MI.INDENDDATE, GETDATE()) >= '01/01/2014')
;


